version: '3.8'

services:
  overssh:
    build: .
    ports:
      - "2222:22"    # SSH port (mapped to 2222 to avoid conflicts with host SSH)
    environment:
      - DEV=false
    volumes:
      # Uncomment if you need to persist data
      # - ./data:/data
    restart: unless-stopped
    networks:
      - overssh-net
    
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - overssh-net
    depends_on:
      - overssh
    
  # Optional: Add a development service
  overssh-dev:
    build: .
    ports:
      - "2223:22"
      - "8081:8080"
    environment:
      - DEV=true
    profiles:
      - dev
    networks:
      - overssh-net

networks:
  overssh-net:
    driver: bridge

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false